name: SpecKit — Analyze Agent Run
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: corepack enable
      - run: pnpm --version || npm i -g pnpm
      - run: pnpm install --frozen-lockfile

      - name: Download agent run logs
        uses: actions/download-artifact@v4
        with:
          name: agent-run-logs
          path: ./agent-logs

      - name: Unpack logs
        run: |
          mkdir -p runs_from_artifact
          tar -xzf agent-logs/agent-run-logs.tar.gz -C runs_from_artifact

      - name: Analyze run logs
        run: |
          pnpm speckit:analyze -- --raw-log "runs_from_artifact/*" \
            --write-rtm RTM.md --out .speckit

      - name: Commit RTM + artifacts (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(speckit): update RTM & .speckit artifacts"
          file_pattern: |
            RTM.md
            .speckit/**

      - name: PR Comment — Run Forensics
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: .speckit/summary.md
