name: speckit-analyze-run

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    name: Analyze agent run logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download agent run logs
        id: download_logs
        uses: actions/download-artifact@v4
        with:
          name: agent-run-logs
          path: agent-run-logs
          if-no-files-found: ignore

      - name: Detect log bundle
        id: check_logs
        run: |
          if compgen -G "agent-run-logs/**/*" > /dev/null; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run analyzer
        if: steps.check_logs.outputs.found == 'true'
        run: pnpm speckit:analyze -- --raw-log "agent-run-logs/**/*"

      - name: Commit run artifacts
        if: steps.check_logs.outputs.found == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update speckit run artifacts"
          branch: ${{ github.head_ref }}
          file_pattern: |
            .speckit/*.json
            .speckit/*.yaml
            .speckit/*.md
            .speckit/requirements.jsonl
            RTM.md
            docs/internal/agents/coding-agent-brief.md

      - name: Post run summary comment
        if: steps.check_logs.outputs.found == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: .speckit/summary.md

      - name: No artifact notice
        if: steps.check_logs.outputs.found != 'true'
        run: echo "No agent-run-logs artifact found. Upload logs to enable run forensics."
